apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb
  namespace: galera
data:
  my.cnf: |-
    [mysqld]
    datadir=
    
    binlog_format=ROW
    default_storage_engine=InnoDB
    innodb_autoinc_lock_mode=2

    wsrep_on=ON
    wsrep_provider=/usr/lib/galera/libgalera_smm.so
    wsrep_cluster_name="k8s_galera_cluster"

    wsrep_cluster_address="gcomm://mariadb-0.mariadb.galera.svc.cluster.local,mariadb-1.mariadb.galera.svc.cluster.local,mariadb-2.mariadb.galera.svc.cluster.local"

    wsrep_node_address=""
    wsrep_node_name=""

    wsrep_sst_method=rsync
  run.sh: |-
    #!/bin/bash

    echo "Determining current pod and statefulset..."
    POD_NAME=$(hostname)
    POD_IP=$(hostname -i)

    cat /config/my.cnf \
        | sed "s/wsrep_node_address=\"\"/wsrep_node_address=\"${POD_IP}\"/" \
        | sed "s/wsrep_node_name=\"\"/wsrep_node_name=\"${POD_NAME}\"/" \
        | sed "s/datadir=/datadir=\/var\/lib\/mysql\/${POD_NAME}/" \
        > /etc/mysql/my.cnf

    CLUSTER_NODES="mariadb-0.mariadb mariadb-1.mariadb mariadb-2.mariadb"

    DATA_DIR="/var/lib/mysql/$POD_NAME"
    GRASTATE_FILE="$DATA_DIR/grastate.dat"

    mkdir -p "$DATA_DIR"
    
    ONLY_NODE=1
    for node in $CLUSTER_NODES; do
      if [ "$node" = "${POD_NAME}.mariadb" ]; then
        continue
      fi
    
      if mysqladmin ping -h "$node" --silent; then
        echo "Detected active MySQL node: $node"
        ONLY_NODE=0
        BOOTSTRAP_REQUIRED=0
        break
      fi
    done
    
    if [ ! -f "$GRASTATE_FILE" ]; then
      if [ "$ONLY_NODE" -eq 1 ]; then
        echo "No active MySQL nodes detected → bootstrapping new Galera cluster"
        exec docker-entrypoint.sh mysqld --wsrep-new-cluster
      else
        echo "No grastate.dat found but other nodes are active → joining existing cluster"
        exec docker-entrypoint.sh mysqld
      fi
    else
      if [ "$ONLY_NODE" -eq 1 ]; then
        # Check if grastate.dat indicates safe_to_bootstrap=1 → if so, bootstrap from existing data instead of starting as a new cluster
        echo "grastate.dat found but no active MySQL nodes detected → checking if safe_to_bootstrap=1 to bootstrap from existing data"
        find /var/lib/mysql -regex '.*grastate.dat' -print0 | while IFS= read -r -d '' file; do
          echo "testing file $file"
          if [ "$(grep -Po 'safe_to_bootstrap:.*\K\d' "$file")" = "1" ]; then
            safe_dir=$(dirname $file)
            if [ "$safe_dir" != "/var/lib/mysql/$POD_NAME" ]; then
              mv "$safe_dir" "/var/lib/mysql/temp-dir"
              mv "/var/lib/mysql/$POD_NAME" "$safe_dir"
              mv "/var/lib/mysql/temp-dir" "/var/lib/mysql/$POD_NAME"
            fi
            echo "grastate.dat indicates safe_to_bootstrap=1 → bootstrapping new Galera cluster from existing data"
            exec docker-entrypoint.sh mysqld
          fi
        done
        echo "grastate.dat does not indicate safe_to_bootstrap=1 → checking other options"
        BASE_DIR="/var/lib/mysql"
    
        BEST_NODE=""
        BEST_SEQNO="-1"
    
        for dir in "$BASE_DIR"/*; do
        [ -d "$dir" ] || continue
    
        FILE="$dir/grastate.dat"
    
        if [ -f "$FILE" ]; then
          SEQNO=$(grep -i "^seqno:" "$FILE" | awk '{print $2}')
        else
          SEQNO="-1"
        fi
    
        # Recover if needed
        if [ "$SEQNO" = "-1" ]; then
          echo "Recovering seqno for $dir..."
          SEQNO=$(mysqld --wsrep-recover --datadir="$dir" 2>&1 \
            | grep -E "Recovered position|WSREP: Recovered position" \
            | tail -1 \
            | sed 's/.*://')
    
          # fallback safety
          if [ -z "$SEQNO" ]; then
            echo "Recovery failed → seqno=-1"
            SEQNO="-1"
          fi
        fi
    
        echo "$dir → seqno=$SEQNO"
    
        if [ "$SEQNO" -gt "$BEST_SEQNO" ]; then
          BEST_SEQNO="$SEQNO"
          BEST_NODE="$dir"
        fi
        done
    
        echo "-----------------------------------"
        echo "Selected bootstrap node: $BEST_NODE"
        echo "With seqno: $BEST_SEQNO"
        if [ "$BEST_NODE" != "/var/lib/mysql/$POD_NAME" ]; then
          mv "$BEST_NODE" "/var/lib/mysql/temp-dir"
          mv "/var/lib/mysql/$POD_NAME" "$BEST_NODE"
          mv "/var/lib/mysql/temp-dir" "/var/lib/mysql/$POD_NAME"
        fi
        sed -i 's/safe_to_bootstrap:.*/safe_to_bootstrap: 1/' /var/lib/mysql/$POD_NAME/grastate.dat
        exec docker-entrypoint.sh mysqld --wsrep-new-cluster
      else
        echo "grastate.dat found but other nodes are active → joining existing cluster"
        exec docker-entrypoint.sh mysqld
      fi
    fi